config/routes.rb
Planet::Application.routes.draw do
  get "planet/index"

  get "planet/contact"

  resources :types do
	resources :sites
  end

  resources :sites

  root :to => "planet#index"

end

app/models/site.rb
class Site < ActiveRecord::Base
   belongs_to :type   #planet_a: Un sitio es de un tipo
end

app/models/type.rb
class Type < ActiveRecord::Base
   has_many :sites   #planet_a: un tipo puede tener muchos sitios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/planet_controller.rb
class PlanetController < ApplicationController
  def index
  end

  def contact
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.xml
  def index
   
   if params[:type_id].nil? or params[:type_id].empty?
      @sites = Site.all
      @tipo = 'Todos los Sitios'
   else
      @sites = Type.find(params[:type_id]).sites
      @tipo = Type.find(params[:type_id]).name
   end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to(@site, :notice => 'Site was successfully created.') }
        format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to(@site, :notice => 'Site was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.xml
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @types }
    end
  end

  # GET /types/1
  # GET /types/1.xml
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/new
  # GET /types/new.xml
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.xml
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to(@type, :notice => 'Type was successfully created.') }
        format.xml  { render :xml => @type, :status => :created, :location => @type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.xml
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to(@type, :notice => 'Type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.xml
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to(types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>Planet Travel Site</title> 
<!-- START:stylesheet --> 
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "planet", :media => "all" %><!-- <label id="code.slt"/> --> 
<!-- END:stylesheet --> 
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> --> 
</head> 
<body id="planet"> 
  <div id="banner"> 
    <%= image_tag("logo3.png") %>
    <%= @page_title || "Planet Travel Site" %><!-- <label id="code.depot.e.title"/> --> 
  </div> 
  <div id="columns"> 
    <div id="side"> 
      <%= link_to "Home", planet_index_path %><br /> 
      <%= link_to "Tipos",  types_path %><br /> 
      
      <% tipos = Type.all %>

      <% tipos.each do |type| %>
	<dl> 
          <dt><%= '- ' %><%= link_to type.name, types_path+'/'+type.id.to_s+'/sites' %></dt> 
        </dl> 
 
      <% end %>
      
      <%= link_to "Sitios", sites_path %><br /> 
      <%= link_to "Contact", planet_contact_path %><br />

    </div> 
    <div id="main"> 

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %><!-- <label id="code.depot.e.include"/> --> 
    </div> 
  </div> 
</body> 
</html> 

app/views/planet/contact.html.erb
<h1>Contacting the Planet Travel Site</h1>
<p>Please send an email to:</p>

<p><a href="mailto:contact@planet.travel.com"> contact@planet.travel.com</a></p>

app/views/planet/index.html.erb
<h1>Wecome to the Planet Travel Site</h1>
<p>This site gathers information from all yes of touristic sites from all over the world and should help you to organize your trips and your holidays.</p>

<%= image_tag('pedriza2-m.png') %>

<p>Feel free to use it for your convenience and pleasure.</p>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 4 %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.collection_select(:type_id, Type.find(:all, :order => :name), :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :zoom %><br />
    <%= f.text_field :zoom %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div id="site_list"> 
  <h1><%= @tipo %></h1> 
 
  <table> 
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td> 
        <%= link_to image_tag(site.image_url, :class => 'list_image'), site %>
      </td> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to site.name, site %></dt> 
          <dd><%= truncate(strip_tags(site.description),
                 :length => 80) %></dd>
        </dl> 
      </td>
 
      <td class="list_actions"> 
        <%= link_to 'Show', site %><br/>
        <%= link_to 'Edit', edit_site_path(site) %><br/>
        <%= link_to 'Destroy', site, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 
 
<br /> 
 
<%= link_to 'New site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<div id="site">
 
  <h1><%= @site.type.name + ': '+ @site.name if @site.type %></h1> 

  <%= image_tag(@site.image_url, :class => 'site_image') %>

  <h3><%= @site.name %></h3> 

  <p><%=sanitize @site.description %></p>

  <div class="position"> 
    <span>
      <b>Latitude:</b>
      <%= @site.latitude %>
    </span>
 
    <span>
       <b>Longitude:</b>
       <%= @site.longitude %>
    </span>
  </div> 

</div> 

<p />
<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<div id="site_list"> 
  <h1>Listado de Tipos</h1> 

  <table> 
  <% @types.each do |type| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to type.name, 'types/'+type.id.to_s+'/sites' %></dt> 
          <dd><%= truncate(strip_tags(type.description),
                 :length => 80) %></dd> 
        </dl> 
      </td> 
 
      <td class="list_actions"> 
        <%= link_to 'Show', type %><br/> 
        <%= link_to 'Edit', edit_type_path(type) %><br/> 
        <%= link_to 'Destroy', type, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @type.description %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>